### ISSUE TITLE
Fails on conversion on certain projects

### ISSUE THREAD

**Issue by cbaker6** [sersoft-gmbh/swift-coverage-action#34]
First, thanks for this action! I’ve been able to use it to get codecov back on repos that use Xcode 13. I’ve found one weird case where it can’t convert the coverage files for the “iOS” project only in the ParseSwift repo. It converts all other OS’s fine. I’ve tried both text and Lcov formats.

There isn’t a lot of console output to debug, but here’s the error https://github.com/parse-community/Parse-Swift/pull/262/checks?check_run_id=3947393464#step:5:23

You can see the PR that runs into the error here: https://github.com/parse-community/Parse-Swift/pull/262

the original PR where I tried the text format is here: https://github.com/parse-community/Parse-Swift/pull/261

**Comment by ffried** [comment]
Thanks for reporting this!
This is indeed weird - I've never seen this before. And unfortunately, `llvm-cov` isn't really talkative.

You can try the following two things (one by one):
- Add the following step before running the `swift-codecov-action` (this enables some debug output):
  ```yaml
  - run: echo "RUNNER_DEBUG=1" >> $GITHUB_ENV
  ```
- Add the following argument to the `swift-codecov-action` step:
  ```yaml
  with:
      target-name-filter: '^ParseSwift$'
  ```

I've noticed that it seems to fail at generating coverage data for the TestHost application. That's why the second step adds a filter.

If these two things don't work let me know. We then need to try to find the cause locally - I'll collect the necessary commands then (after running a build locally).
